/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crearcalculadora;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import java.awt.Desktop;
import java.io.File;


public class FRM_CALCULADORA extends javax.swing.JFrame {
public float primernumero;
public float segundonumero;
public String operador;
public String bitacoraContenido;



//instanciar clase
Bitacota objeto = new Bitacota();

    public void setBtn_opc(JButton btn_opc) {
        this.btn_opc = btn_opc;
    }

    public JButton getBtn_opc() {
        return btn_opc;
        
    }

    public void setBtn_bitacoraContenido(JButton btn_bitacoraContenido) {
        this.btn_bitacoraContenido = btn_bitacoraContenido;
    }

    public JButton getBtn_bitacoraContenido() {
        return btn_bitacoraContenido;
    }
  
    public FRM_CALCULADORA() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_entrada = new javax.swing.JLabel();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_multiplicacion = new javax.swing.JButton();
        btn_div = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_opc = new javax.swing.JButton();
        btn_bitacoraContenido = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        lbl_entrada.setBackground(new java.awt.Color(255, 255, 255));
        lbl_entrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_entrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_entrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_entrada.setOpaque(true);
        lbl_entrada.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbl_entradaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btn_1.setText("1");
        btn_1.setOpaque(true);
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_suma.setText("+");
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });

        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_resta.setText("-");
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });

        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_multiplicacion.setText("*");
        btn_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicacionActionPerformed(evt);
            }
        });

        btn_div.setText("/");
        btn_div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divActionPerformed(evt);
            }
        });

        btn_punto.setText(".");
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });

        btn_igual.setText("=");
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });

        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_opc.setText("Manual");
        btn_opc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opcActionPerformed(evt);
            }
        });

        btn_bitacoraContenido.setText("Historial");
        btn_bitacoraContenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bitacoraContenidoActionPerformed(evt);
            }
        });

        btn_new.setText("Nuevo");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(lbl_entrada, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_opc)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_bitacoraContenido))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_bitacoraContenido)
                    .addComponent(btn_opc)
                    .addComponent(btn_new))
                .addGap(12, 12, 12)
                .addComponent(lbl_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_div, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
              if ( this.lbl_entrada.getText().equals("+")||this.lbl_entrada.getText().equals("-")||this.lbl_entrada.getText().equals("*")||this.lbl_entrada.getText().equals("/"))
          {
                 this.lbl_entrada.setText(" ");  
          }
         this.lbl_entrada.setText(this.lbl_entrada.getText()+"1"); 
    
        objeto.Bitacora("1");       
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divActionPerformed
 this.primernumero=Float.parseFloat(this.lbl_entrada.getText());
       this.operador= "/";
       this.lbl_entrada.setText("");  
           }//GEN-LAST:event_btn_divActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        
        if ( this.lbl_entrada.getText().equals("+")||this.lbl_entrada.getText().equals("-")||this.lbl_entrada.getText().equals("*")||this.lbl_entrada.getText().equals("/"))
          {
                 this.lbl_entrada.setText(" ");  
          }
         this.lbl_entrada.setText(this.lbl_entrada.getText()+"2"); 
    
        objeto.Bitacora("2");
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
                if ( this.lbl_entrada.getText().equals("+")||this.lbl_entrada.getText().equals("-")||this.lbl_entrada.getText().equals("*")||this.lbl_entrada.getText().equals("/"))
          {
                 this.lbl_entrada.setText(" ");  
          } this.lbl_entrada.setText(this.lbl_entrada.getText()+"3");        
                  objeto.Bitacora("3");

    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
               
        if ( this.lbl_entrada.getText().equals("+")||this.lbl_entrada.getText().equals("-")||this.lbl_entrada.getText().equals("*")||this.lbl_entrada.getText().equals("/"))
          {
                 this.lbl_entrada.setText(" ");  
          }this.lbl_entrada.setText(this.lbl_entrada.getText()+"4");        
                  objeto.Bitacora("4");

    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
              if ( this.lbl_entrada.getText().equals("+")||this.lbl_entrada.getText().equals("-")||this.lbl_entrada.getText().equals("*")||this.lbl_entrada.getText().equals("/"))
          {
                 this.lbl_entrada.setText(" ");  
          } this.lbl_entrada.setText(this.lbl_entrada.getText()+"5");
                            objeto.Bitacora("5");

    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
             if ( this.lbl_entrada.getText().equals("+")||this.lbl_entrada.getText().equals("-")||this.lbl_entrada.getText().equals("*")||this.lbl_entrada.getText().equals("/"))
          {
                 this.lbl_entrada.setText(" ");  
          }  this.lbl_entrada.setText(this.lbl_entrada.getText()+"6"); 
                            objeto.Bitacora("6");

    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
              if ( this.lbl_entrada.getText().equals("+")||this.lbl_entrada.getText().equals("-")||this.lbl_entrada.getText().equals("*")||this.lbl_entrada.getText().equals("/"))
          {
                 this.lbl_entrada.setText(" ");  
          } this.lbl_entrada.setText(this.lbl_entrada.getText()+"7");   
                            objeto.Bitacora("7");

    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
              if ( this.lbl_entrada.getText().equals("+")||this.lbl_entrada.getText().equals("-")||this.lbl_entrada.getText().equals("*")||this.lbl_entrada.getText().equals("/"))
          {
                 this.lbl_entrada.setText(" ");  
          } this.lbl_entrada.setText(this.lbl_entrada.getText()+"8");
                            objeto.Bitacora("8");

    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
            if ( this.lbl_entrada.getText().equals("+")||this.lbl_entrada.getText().equals("-")||this.lbl_entrada.getText().equals("*")||this.lbl_entrada.getText().equals("/"))
          {
                 this.lbl_entrada.setText(" ");  
          }   this.lbl_entrada.setText(this.lbl_entrada.getText()+"9");
                            objeto.Bitacora("9");

    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
            if ( this.lbl_entrada.getText().equals("+")||this.lbl_entrada.getText().equals("-")||this.lbl_entrada.getText().equals("*")||this.lbl_entrada.getText().equals("/"))
          {
                 this.lbl_entrada.setText(" ");  
          }   this.lbl_entrada.setText(this.lbl_entrada.getText()+"0"); 
                            objeto.Bitacora("0");

    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
       this.segundonumero=Float.parseFloat(this.lbl_entrada.getText());
       switch(this.operador){
           case "+":this.lbl_entrada.setText(sincero(this.primernumero + this.segundonumero));
       }
       this.segundonumero=Float.parseFloat(this.lbl_entrada.getText());
       switch(this.operador){
           case "-":this.lbl_entrada.setText(sincero(this.primernumero - this.segundonumero));
       }
       this.segundonumero=Float.parseFloat(this.lbl_entrada.getText());
       switch(this.operador){
           case "*":this.lbl_entrada.setText(sincero(this.primernumero * this.segundonumero));
       }
       this.segundonumero=Float.parseFloat(this.lbl_entrada.getText());
       switch(this.operador){
           case "/":this.lbl_entrada.setText(sincero(this.primernumero / this.segundonumero));
       }
       objeto.Bitacora(" = " + this.lbl_entrada.getText()+"\n");
    }//GEN-LAST:event_btn_igualActionPerformed

    private void lbl_entradaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbl_entradaAncestorAdded
    }//GEN-LAST:event_lbl_entradaAncestorAdded

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        this.lbl_entrada.setText(" "); 
        this.primernumero=0;
        this.segundonumero=0;

    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
            //validamos que el usuario al presionar varias veces un operador logico no de error
        try {
          this.primernumero+=Float.parseFloat(this.lbl_entrada.getText());
        } catch (NumberFormatException e) {
            System.out.println("Error: No se puede convertir el texto a float.");
        }
       this.operador= "+";
       objeto.Bitacora("+");
       this.lbl_entrada.setText("+");    
       
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
try {
          this.primernumero=Float.parseFloat(this.lbl_entrada.getText());
        } catch (NumberFormatException e) {
            System.out.println("Error: No se puede convertir el texto a float.");
        }
    this.operador= "-";
    objeto.Bitacora("-");
    this.lbl_entrada.setText("-"); 

    }//GEN-LAST:event_btn_restaActionPerformed

    private void btn_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicacionActionPerformed
      try {
          this.primernumero+=Float.parseFloat(this.lbl_entrada.getText());
        } catch (NumberFormatException e) {
            System.out.println("Error: No se puede convertir el texto a float.");
        }
       this.operador= "*";
       objeto.Bitacora("*");
       this.lbl_entrada.setText("*");       // TODO add your handling code here:
    }//GEN-LAST:event_btn_multiplicacionActionPerformed

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
       try {
          this.primernumero+=Float.parseFloat(this.lbl_entrada.getText());
        } catch (NumberFormatException e) {
            System.out.println("Error: No se puede convertir el texto a float.");
        }
       this.operador= ".";
       objeto.Bitacora(".");
       this.lbl_entrada.setText(".");      

    }//GEN-LAST:event_btn_puntoActionPerformed

    private void btn_bitacoraContenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bitacoraContenidoActionPerformed
    try {
        // Obtén la ruta absoluta del archivo "Historial.txt"
        String filePath = "Historial.txt";
        // Crea un objeto File con la ruta del archivo
        File file = new File(filePath);
        // Verifica si el archivo existe y es un archivo
        if (file.exists() && file.isFile()) {
            // Abre el archivo con el programa predeterminado
            Desktop.getDesktop().open(file);
        } else {
            System.out.println("El archivo no existe o no es un archivo válido.");
        }
    } catch (IOException ex) {
        ex.printStackTrace();
        System.out.println("Error al intentar abrir el archivo.");
    }
       
    }//GEN-LAST:event_btn_bitacoraContenidoActionPerformed

    private void btn_opcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opcActionPerformed
        // TODO add your handling code here:
        try {
        // Obtén la ruta absoluta del archivo "Historial.txt"
        String filePath = "C:\\Users\\salaz\\OneDrive\\Documentos\\NetBeansProjects\\crearcalculadora\\src\\crearcalculadora\\Manual.txt";
        // Crea un objeto File con la ruta del archivo
        File file = new File(filePath);
        // Verifica si el archivo existe y es un archivo
        if (file.exists() && file.isFile()) {
            // Abre el archivo con el programa predeterminado
            Desktop.getDesktop().open(file);
        } else {
            System.out.println("El archivo no existe o no es un archivo válido.");
        }
    } catch (IOException ex) {
        ex.printStackTrace();
        System.out.println("Error al intentar abrir el archivo.");
    }
    }//GEN-LAST:event_btn_opcActionPerformed

    public String sincero(float resultado){
        String retorno= "";
            retorno=Float.toString(resultado);
            if(resultado%1==0){
                retorno=retorno.substring(0, retorno.length()-2);
                
            }        
        
         return retorno;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_CALCULADORA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_CALCULADORA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_CALCULADORA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_CALCULADORA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_CALCULADORA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_bitacoraContenido;
    private javax.swing.JButton btn_div;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_multiplicacion;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_opc;
    private javax.swing.JButton btn_punto;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_suma;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_entrada;
    // End of variables declaration//GEN-END:variables
}
